name: ood
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.8.*
  - jupyterlab
  - seaborn
  - pip
  - pytorch
  - torchvision
  - cudatoolkit
  - pip:
      - ftfy
      - regex
      - tqdm
      - git+https://github.com/openai/CLIP.git
      - sklearn